### ISSUE TITLE
SPIKE: Keyboard accessible reordering of blocks

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#455] opened 2018-10-17 23:28 UTC
It is currently not possible on `master` to re-order blocks on a page with keyboard actions. We should investigate the best way to implement functionality that provides keyboard access to reordering functionality.

Drag and drop will be implemented via #285 but `https://github.com/react-dnd/react-dnd` doesn't provide accessible functionality out of the box.

Ideas (in likely priority)
~1. Ensure inline adding of blocks can be tabbed to:~ split to #627
![image](https://user-images.githubusercontent.com/15868440/47121853-d5fda300-d2d0-11e8-979f-1fdeff6788bc.png)
2. Investigate if accessibility can be built on top of `react-dnd/react-dnd` 
3. Investigate recent accessibility improvements in `https://github.com/atlassian/react-beautiful-dnd` although additional development will be expected.
4. Look into a 'move block up/down' function to +1/-1 the order of the block on the page

**Comment by clarkepaul** [comment] 2018-10-18 06:49
Seems like a decent article on this matter [here](https://dev.opera.com/articles/accessible-drag-and-drop/), and [demo](https://dev.opera.com/articles/accessible-drag-and-drop/example.html#kbdinstructions).

**Comment by ScopeyNZ** [comment] 2018-10-18 08:56
Here's the beautiful DND examples: https://react-beautiful-dnd.netlify.com/?selectedKind=single%20vertical%20list&selectedStory=basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

The DND PR is good to go - would be interested to look at a refactor to this library but it might mean starting from scratch.

**Comment by newleeland** [comment] 2018-12-04 03:06
Don't think this requires designs, react-beautiful-dnd seems to have built-in drag-n drop for screen readers. https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/screen-reader.md

**Comment by NightJar** [comment] 2019-07-17 05:19
I'm not an expert on accessibility, and for this reason I think transferring to the new `react-beautiful-dnd` library would be a superior option to attempting to self-engineer (self as in team) a retrofit of accessibility hints, controls, and usage flows to the current solution. So the outcome of this investigation has been based/biased around this. Both libraries are well maintained, I don't see one as being preferable to the other on this criterion alone.

react-dnd has it's roots in `silverstripe/admin` so we'd have to update that to take advantage of a new library. To my knowledge we're the only ones consuming this export - but I did not attempt to check this assumption.

We are using `DragSource` and `DropTarget` from the "Legacy decorator API" in `react-dnd` rather than the newer `useDrag` and `useDrop`, where I personally find the legacy API a little easier to follow - plus this is more relatable to the `Draggable` and `Droppable` API provided by `react-beautiful-dnd`. This is a kind of win for an easy port I think - the implementation details are mostly transferrable; The wrappers provide props to child components that update with dragging state. The details change, but the concept remains the same.

`react-dnd` is activated via `lib/withDragDropContext` in admin, which is a simple wrapper around exporting the library's wrapper with a backend attached (the HTML5 backend, specifically). This is an internal that could hopefully be updated without need for making a new release of webpack config.

The `react-beautiful-dnd` library supplies an element of the same name `DragDropContext` for the creation of the drag and drop area, however takes different properties - the important difference being that the hooks for updating before, during and after a drag are contained here, rather than on the `Draggable`/`DragSource` and `Droppable`/`DropTarget` as per `react-dnd`.

Other properties living on `Draggable`/`DragSource` and `Droppable`/`DropTarget` seem mostly transferrable, although they do change name (e.g. `canDrop` becomes `isDropDisabled`). I don't think this would be a huge burden at all.

Switching library here would also have a knock on affect, in that `react-beautiful-dnd` supports dragging between lists, which is asked about every so often in the community, by people adding more than one `ElementalArea` to their objects.

I also think the [combining feature](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/droppable.md#combining) would provide a head start for #332 - allowing existing elements t be dragged in and out of a Layout Block.

Implementation intro:
https://egghead.io/lessons/react-reorder-a-list-with-react-beautiful-dnd

**Comment by ScopeyNZ** [comment] 2019-07-17 05:43
There's still a couple of oddities about our use case that might need to be considered.

We have drag areas within drag areas - that's why admin exposes a HOC (`withDragDropContext`). ReactDND has an issue with two separate contexts being created so they need to share the same one. Not sure if this is going to be an issue if we have ReactDND inside a React-Beautiful-DND? For reference this is when you have an `UploadField` within an in-line edit form.

Our UI for dragging is a little custom. We leave an indication of the current position within our list of blocks and we insert a line to show where the element will drop. I assume that this will probably have to change with ReactDND? It forces you down the route of showing where it'll land and not indicating the existing location...

Currently we use another "power feature" (of sorts) with ReactDND - the ability to have custom drag previews for our elements. We do this because the in-line edit forms can be pretty massive to be dragging up and down the screen. I remember seeing an issue saying this wasn't possible with ReactDND - although you could re-render the component by using some `isDragging` prop. We might need to do some POC work to see if this works though as I have a feeling this could cause issues when the draggable area suddenly changes size on you.

Playing a little bit of a devils' advocate here but I think we need to be sure that we're not going to create a big project for ourselves by diving into "switch out the DND library" - especially when there's this quote on the beautiful DND page:

> However, it does not provide the breadth of functionality offered by react-dnd. So react-beautiful-dnd might not be for you depending on what your use case is.

**Comment by robbieaverill** [comment] 2019-07-17 13:21
I'm not overly familiar with the implementation of the drag and drop library, but I'd tend to agree with @ScopeyNZ's comments - replacing the library seems to me like it'd be more work than implementing keyboard accessibility in the library we already have. 

I can't find anything obvious in the docs or issue tracker for it relating to being able to control the drag/drop events with keyboard buttons, however I think that we could either add it ourselves, or simply add a "Move down" and "Move up" option to the actions dropdown to compensate for it if that's too difficult.

**Comment by Cheddam** [comment] 2019-07-17 21:42
I wouldn't be too quick to assume creating a good a11y experience on our own will be easier than switching library, particularly when `react-dnd` makes no mention of it in their documentation whilst `react-beautiful-dnd` goes [step by step](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/screen-reader.md) through the different audible descriptions it provides.

It was discussed at standup that we've missed another option, though: Using standard buttons or options in the Actions panel to enable shifting blocks up or down for keyboard access / screen readers. This would be less efficient from a usability perspective, but easier to implement well. @newleeland might have some designs for this?

**Comment by NightJar** [comment] 2019-07-17 21:51
> There's still a couple of oddities about our use case that might need to be considered.
> 
> We have drag areas within drag areas - that's why admin exposes a HOC (`withDragDropContext`). ReactDND has an issue with two separate contexts being created so they need to share the same one. Not sure if this is going to be an issue if we have ReactDND inside a React-Beautiful-DND? For reference this is when you have an `UploadField` within an in-line edit form.



> Our UI for dragging is a little custom. We leave an indication of the current position within our list of blocks and we insert a line to show where the element will drop. I assume that this will probably have to change with ReactDND? It forces you down the route of showing where it'll land and not indicating the existing location...

I don't think this is true. I note the difference between a DragLayer (`react-dnd`) and not having one, but I believe this is replaced by 'Responder' properties on the context (https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/responders.md#ondragupdate-optional), which I think can still achieve the same thing (showing drop indicators, etc.)

> Currently we use another "power feature" (of sorts) with ReactDND - the ability to have custom drag previews for our elements. We do this because the in-line edit forms can be pretty massive to be dragging up and down the screen. I remember seeing an issue saying this wasn't possible with ReactDND - although you could re-render the component by using some `isDragging` prop. We might need to do some POC work to see if this works though as I have a feeling this could cause issues when the draggable area suddenly changes size on you.

This may be true. I did not see any indication of the functionality for [horseface to be shown on a drag](http://react-dnd.github.io/react-dnd/docs/tutorial#concluding-words). I think it would probably be possible, but as with the link above about the responders, the update function docs do warn: `It is important that you not do too much work as a result of this function as it will slow down the drag.`

> Playing a little bit of a devils' advocate here but I think we need to be sure that we're not going to create a big project for ourselves by diving into "switch out the DND library" - especially when there's this quote on the beautiful DND page:
> 
> > However, it does not provide the breadth of functionality offered by react-dnd. So react-beautiful-dnd might not be for you depending on what your use case is.

Reference: [Not for everyone ✌️](https://github.com/atlassian/react-beautiful-dnd#not-for-everyone-️)
This quote is in the context that `react-beautiful-dnd` is build specifically for ordering lists, where `react-dnd` is more generic and one should consider their use case. I did, an `ElementalEditor` is made up of a single vertical [list](https://github.com/dnadesign/silverstripe-elemental/blob/4.1.0/client/src/components/ElementEditor/ElementList.js#L54) of elements. On the other hand the example for `react-dnd` is dragging a knight around a chessboard - not quite a single list.

> I can't find anything obvious in the docs or issue tracker for it relating to being able to control the drag/drop events with keyboard buttons, however I think that we could either add it ourselves, or simply add a "Move down" and "Move up" option to the actions dropdown to compensate for it if that's too difficult.

I agree with @Cheddam on this - I would not presume that creating good a11y interfaces should be simple, otherwise I do not think there would be an industry specialisation around this. Keeping in mind that anything we build will be ours to maintain, I think the ability to 'outsource' or offload as much of that as possible is a good choice.

Adding 'move up' and 'move down' options to a menu seems only a viable option if the menu were to stay open and maintain focus between move operations, so one could move an item up and down in succession quickly, rather than tedious menu interactions each time.

On this though I have forgotten to mention that I also considered that we have a drag handle - although we don't use it. Selecting a block currently and activating it will open or collapse the inline edit form - this will need to change, or we would have to activate the drag only when the handle is active - which would mean making that 'tab-able' - but would also be a tricky consideration as it is the entire element header that is the mouse activated drag handle. This will be a challenge in either library. Which ultimately puts more weight on the "buttons" approach.

**Comment by robbieaverill** [comment] 2019-07-22 09:24
Sorry, I wasn't trying to suggest that it would be simple, but rather that we should weigh up the effort versus reward. Here's where I see the options for this issue now:

### Option 1: replace react-dnd with react-beautiful-dnd

Pros:

* It has better support for accessibility/screen readers/keyboards
* We aren't implementing too much of our own custom accessibility code

Cons:

* An amount of work will be required to switch the library, regression test the drag and drop features, and ensure that the new library provides the support we need for accessibility

### Option 2: keep react-dnd and implement out own keyboard accessibility events

Pros:

* Lower impact to the existing code, since we aren't switching libraries
* Potentially faster

Cons:

* Potentially introducing more maintenance burden by writing our own keyboard handling events for drag and drop
* It may end up being more work than replacing the library with react-beautiful-dnd

### Option 3: add new options to the more actions menu to move elements

Example:

![image.png](https://images.zenhubusercontent.com/58409bdab9dc3c622022d20e/282baea1-0c13-4d3b-9246-85c4f9e06490)

Pros:

* Easy and fast to implement
* Low impact to existing code

Cons:

* Probably doesn't match the UX designs
* Adds a little more bloat to the more actions menu

### Option 4: add tab key accessible "up" and "down" options in the blue "add new element" bar

Example:

![image.png](https://images.zenhubusercontent.com/58409bdab9dc3c622022d20e/32f2f07c-6f56-4306-bf23-f2c4999e0a10)

(Except use icons instead of text)

Pros:

* Same as option 3
* Doesn't bloat the more actions menu like option 3 would

Cons:

* Same as option 3 (minus the menu bloat)

---

@silverstripe/creative-commoners please vote on this so we can agree on the way forward, and then close this spike =)

**Comment by Cheddam** [comment] 2019-07-22 22:00
For Option 4, I don't think the up / down could live in the "add new element" area - the ownership of the buttons would be unclear. Instead, I'd see them living next to the Actions menu. This would require more tabbing to navigate to the Actions menu, making the interaction less convenient - but accessible controls are far more important than convenient ones.

Given the reluctance to switch, and the fact that `react-dnd` is used elsewhere in SilverStripe, I'm opting to vote for Option 2 at this stage - on the basis that we actually take the time to make this work well. I'd also personally be happy with, and am voting for, Option 4 (with the caveats above).

**Comment by clarkepaul** [comment] 2019-07-22 23:17
My suggestion would be to make an area near the drag icon tab-able with the arrow icon actions to move the item up or down. The drag handle would help to provide context as to what the actions do. The options dropdown is going to get overloaded with more actions soon or through a project's development. 
<img width="470" alt="Pasted_Image_23_07_19__11_11_AM" src="https://user-images.githubusercontent.com/555033/61671342-44c5cc00-ad3b-11e9-869e-a68157296042.png">
 (duplicate, move, other tabs).

**Comment by NightJar** [comment] 2019-07-22 23:28
Also to be clear:
Option 4 is not viable; This menu (or this hover bar rather) is not accessible via keyboard navigation - it only appears on hover - which is of course a mouse event.

**Comment by robbieaverill** [comment] 2019-07-22 23:29
That sounds like a fixable bug to me :-)

**Comment by NightJar** [comment] 2019-07-22 23:40
I also don't agree that it's a good solution (but that's what voting is for). I like Paul's suggestion above better :)

**Comment by robbieaverill** [comment] 2019-07-22 23:42
Yeah I agree- feel fre esto change option 4 to Paul’s suggestion. My vote would stay the same

**Comment by NightJar** [comment] 2019-07-23 00:18
OK, I did that :)

**Comment by ScopeyNZ** [comment] 2019-07-23 00:26
I voted ❤️ 🚀 and 👀 . I think that ❤️ is a bit of a pipe-dream but I like the idea of doing both 🚀 and 👀 . I even think 🚀 will be minimal effort.

**Comment by NightJar** [comment] 2019-07-23 00:39
Neat, so the outcome of this SPIKE is to implement "move up" and "move down" buttons on the ElementHeader, with a stretch goal of having them available as actions in the more options menu also.
As a side note the drag handle will need to be permanently visible when an element is focussed at least, probably always, at best.

I'll update the OP.

**Closed** 2019-07-23 00:41 UTC
Labels: affects/v4, change/minor, effort/medium, impact/medium, type/UX, type/enhancement, type/frontend
