### ISSUE TITLE
Has changes indicator remaining after publish of page and after publishing block successfully

### ISSUE THREAD

**Issue by clarkepaul** [dnadesign/silverstripe-elemental#667] opened 2019-05-14 23:48 UTC
This icon is still remaining after a successful page publish. I've even tried to publish the block independently from the page and it still remains. The expectation is that this indicator disappears.

<img width="225" alt="Pasted_Image_15_05_19__11_41_AM" src="https://user-images.githubusercontent.com/555033/57739340-553c4380-7707-11e9-99cc-004880ea870a.png">

SilverStripe 4.3.1 (CWP 2.2)

**Comment by ScopeyNZ** [comment] 2019-05-15 00:04
Can you provide the version of elemental? There's been a bunch of fixes with this indicator recently

**Comment by clarkepaul** [comment] 2019-05-15 00:14
Sorry don't know but you should be able to get it from the CWP version. I'm just using the demo.

**Comment by clarkepaul** [comment] 2019-05-15 00:18
Elemental 3.0.0 according to the site module report.

**Comment by ScopeyNZ** [comment] 2019-05-15 00:29
I think this was fixed in 4.0.3 with 
> FIX Ensuring state is destroyed correctly & updating publish action (Guy Marriott)
https://github.com/dnadesign/silverstripe-elemental/commit/472dde0b8d36128995190a4177305b79f554bf21

The additional information against that change is:
> The publish action was not reinitialising the redux form which meant the pristine state was never updated

ie. The new "published" state was not being considered after publishing before that fix.

I've had a quick look at 4.0.4 and I can't reproduce there.

**Closed by ScopeyNZ** 2019-05-15 00:29 UTC
Labels: affects/v4, change/patch, effort/medium, impact/medium, type/bug
