### ISSUE TITLE
Saving a page with blocks or without blocks causes an Invariant Violation

### ISSUE THREAD

**Issue by swytch** [dnadesign/silverstripe-elemental#1061] opened 2023-06-12 22:15 UTC
Uncaught (in promise) Invariant Violation: Invariant Violation: 20

Packages installed are:

 "silverstripe/tagfield": "^3.0",
 "silverstripe/recipe-cms": "^5",
 "dnadesign/silverstripe-elemental": "^5"

Sample repo here https://github.com/swytch/bugs - unsure if this is impacting the other bugs here.

**Comment by GuySartorelli** [comment] 2023-06-14 23:24
Closing as a duplicate of https://github.com/silverstripe/silverstripe-elemental/issues/950

**Closed as not planned by GuySartorelli** 2023-06-14 23:24 UTC
