### ISSUE TITLE
Saving images when using inline blocks causes JS errors.

### ISSUE THREAD

**Issue by swytch** [dnadesign/silverstripe-elemental#1063] opened 2023-06-12 22:30 UTC
Adding a new image / updating an image, fires a POST to a missing url and then errors in javascript.   Same repo to replicate here : https://github.com/swytch/bugs.

This doesn't inhibit saving the block.

However using the nested block in the same repo, and adding an image inside will stop the image from saving.  Uncaught SyntaxError: Unexpected token '<', " - which looks like it's returning the HTML for the editform instead of JSON.  I think these are related, so I'm sticking both issues in here.

**Comment by GuySartorelli** [comment] 2023-06-14 23:32
> Adding a new image / updating an image, fires a POST to a missing url and then errors in javascript

I can't reproduce this. Please add a series of explicit step-by-step instructions for reproducing this.

> using the nested block in the same repo, and adding an image inside will stop the image from saving. Uncaught SyntaxError: Unexpected token '<', "

I can't reproduce this either. Please add a second set of step-by-step instructions for reproducing this one.

**Comment by baukezwaan** [comment] 2024-10-11 14:50
We are experiencing probably the same issue. Maybe we can shed some light on how to reproduce this. 

First some context / findings:
- we are using Elemental 5.2.3 and SS 5.2.12
- we are using Elemental in BlogPosts, so the ElementalArea is loaded not in Pages but Blog (admin/news/)
- if we edit the same page in the pages section, the are no js-errors and the page can be saved without problems 
  - so instead of `/admin/news/SilverStripe-Blog-Model-BlogPost/EditForm/field/SilverStripe-Blog-Model-BlogPost/item/659/edit/`
  - use the same ID in a different pages-section: `/admin/pages/edit/show/659/`
- using `inlineEditable` solves the problem also

Reproduction steps
- set the `DNADesign\Elemental\Extensions\ElementalPageExtension` on the BlogPost pagetype
- create an Element with a text and image
- in the CMS, create a new blogpost and add the text-image element
- add an image and some text, save the page
- observe the console error `Uncaught SyntaxError: Unexpected token '<', "`
  - the expected JSON is indeed no json, but the HTML of the form.
  - this is caused by the URL returning HTML instead of JSON `/admin/news/SilverStripe-Blog-Model-BlogPost/EditForm/field/SilverStripe-Blog-Model-BlogPost/item/659/ItemEditForm/` 

Maybe the screencast makes it a little better to understand. The first part is editing in the Blog-section, the second part in the Pages-section (yet it is the same blogpost / page):


https://github.com/user-attachments/assets/4dba21c9-138b-4e6a-9979-593a057944fd

**Comment by GuySartorelli** [comment] 2024-12-16 20:53
@baukezwaan can you please check if this is fixed in 5.3.1+?
I think https://github.com/silverstripe/silverstripe-elemental/pull/1267 will have resolved it.

**Comment by baukezwaan** [comment] 2024-12-18 09:39
@GuySartorelli yes, just checked to see if updating to the latest version would fix this issue. 

I have upgraded `dnadesign/silverstripe-elemental (5.2.3 => 5.3.4)` and now the image does work while editing the element inline.

Thanks!

**Comment by GuySartorelli** [comment] 2024-12-18 19:59
Awesome. Closing this as resolved.

**Closed as completed by GuySartorelli** 2024-12-18 19:59 UTC
Labels: type/bug, affects/v5
