### ISSUE TITLE
IE11 uri gets duplicated when trying to edit an item

### ISSUE THREAD

**Issue by ningensei** [dnadesign/silverstripe-elemental#683] opened 2019-06-27 01:07 UTC
Elemental Version: 4.1.0
SilverStripe Version: 4.4.0

The url is malformed when trying to edit an ElementalArea item. 

This is what I get in chrome:
/admin/pages/edit/EditForm/6/field/ElementalArea/item/2/edit

and this in IE11:
/admin/pages/edit/show/admin/pages/edit/EditForm/6/field/ElementalArea/item/2/edit

**Comment by robbieaverill** [comment] 2019-06-30 20:50
How do you edit the ElementalArea? Elemental doesn't give you a way to do this directly, per-se. It gives you the CMS area interface listing blocks etc, is that what you're referring to? If so, where does the URL come into play for that?

**Comment by HJGreen** [comment] 2019-07-03 05:24
I have a similar issue with IE11, but only for Elements where `$inline_editable = false`

Elemental Version: **4.0.3**
SilverStripe Framework/CMS Version: **4.4.1**

---

### Steps to reproduce:

- Open a page in the CMS which contains Elemental blocks
- Click one of the blocks in the list to access its edit view

### Expected:

- Browser navigates to the edit screen

### Actual:

- Browser returns a 404 page


---

The URL which returns a 404 is in the same format as reported originally by @ningensei. Comparing it to the expected URL, it appears there is an additional `admin/pages/edit/show/` at the start of the path.

My hunch is that there is an issue in the JavaScript that handles the page navigation, however I don't see any errors logged in the console.

**Comment by HJGreen** [comment] 2019-07-03 05:56
I've been debugging in IE's devtools and it seems the issue is due to relative/absolute URLs, and I've tracked it down to this line:

https://github.com/dnadesign/silverstripe-elemental/blob/47ee8710488f9819c98dbd6b5306bb1ac6797277/client/src/components/ElementEditor/Element.js#L148

Here the value of `link` is `admin/pages/edit/EditForm/6/field/ElementalArea/item/2/edit`

Chrome/Firefox seem to treat that as an absolute URL and replace the existing path. IE11 seems to treat it as a relative URL and only replaces the very last section of the current URL.

A naive solution would be prepending `link` with a forward slash so that it's always treated as an absolute URL, but I'm not sure whether that would have any consequences elsewhere.

**Comment by brynwhyman** [comment] 2019-07-04 22:21
Given the report implies some blocks aren't editable through the UI for IE11, which is a supported browser, bumping this to critical

**Comment by robbieaverill** [comment] 2019-07-15 12:02
Ah yep, easy to reproduce with a "Form block" which comes with dnadesign/silverstripe-elemental-userforms. Thanks.

**Comment by robbieaverill** [comment] 2019-07-15 12:11
PR at #690

**Comment by ScopeyNZ** [comment] 2019-07-16 03:08
Closed by #690

**Closed by ScopeyNZ** 2019-07-16 03:08 UTC
Labels: affects/v4, change/patch, effort/easy, impact/critical, type/bug
