### ISSUE TITLE
ElementsForSearch returns empty during Solr search indexing

### ISSUE THREAD

**Issue by thats4shaw** [dnadesign/silverstripe-elemental#362] opened 2018-08-29 02:21 UTC
This is a strange one and I swear this was working previously however I'm not having any luck retracing my steps.

I'm finding that ElementsForSearch method appears to be returning empty in the context of Solr search indexing.

The CMS search is working as per normal and I'm just using the basic indexer supplied by this module.

I initially wondered if it was some what related to https://github.com/dnadesign/silverstripe-elemental/issues/228 and https://github.com/dnadesign/silverstripe-elemental/issues/271 but it's finding the templates fine.  

From my debugging it appears $ElementControllers is empty in `templates/DNADesign/Elemental/Models/ElementalArea.ss`.

Module versions:
```
dnadesign/silverstripe-elemental 3.0.x-dev a643f4d 
silverstripe/fulltextsearch  3.3.1
silverstripe/fulltextsearch-localsolr dev-master f2a799e
silverstripe/recipe-cms  4.2.1 
```

**Comment by robbieaverill** [comment] 2018-08-29 02:27
There may have been a regression. If so, we can revert it since it hasn't been released yet

**Comment by robbieaverill** [comment] 2018-08-29 23:50
@thats4shaw are you able to test this with those changes reverted?

**Comment by thats4shaw** [comment] 2018-08-29 23:52
Absolutely @robbieaverill.  What changes in particular?

**Comment by robbieaverill** [comment] 2018-08-29 23:54
Sorry, the latest change we merged related to this was https://github.com/dnadesign/silverstripe-elemental/pull/342

**Closed as completed** 2018-08-30 05:24 UTC
Labels: type/bug, affects/v4
