### ISSUE TITLE
TinyMCE Inline Toolbar placement

### ISSUE THREAD

**Issue by christopherdarling** [dnadesign/silverstripe-elemental#655] opened 2019-04-18 09:10 UTC
SilverStripe 4.3.3

When using a `HTMLEditorField` inside a Elemental block, the placement of the inline toolbar (https://github.com/silverstripe/silverstripe-admin/blob/0f0a0a064bf4a10f4122795fb56ecf69a1da65cd/client/src/components/TinymceInlineToolbar/TinymceInlineToolbar.js) breaks when the link is not the first paragraph. This only appears to be an issue when using the inline editing feature of Elemental (issue not present when using the field directly on Page or via a typical GridField). For example;

**Correct placement** - when link is first paragraph
![image](https://user-images.githubusercontent.com/178039/56349835-51c5a300-61c1-11e9-8110-bf155c0c7ba3.png)

**Incorrect placement** - when link is on a second paragraph (see the bottom of the popup near the cursor at the top of the screenshot)
![image](https://user-images.githubusercontent.com/178039/56349820-48d4d180-61c1-11e9-9d0e-061497347b48.png)

**Comment by robbieaverill** [comment] 2019-07-17 15:14
Reproduced, I think you need to be in the mobile viewport to experience this

**Comment by christopherdarling** [comment] 2019-07-17 15:18
Thanks Robbie, I can confirm that this was also on desktop

**Comment by robbieaverill** [comment] 2019-07-17 15:20
I can also confirm that this is an elemental specific problem, not happening on regular page types

**Comment by robbieaverill** [comment] 2019-07-17 16:19
PR at https://github.com/silverstripe/silverstripe-admin/pull/910. I've tested the popup on each possible line until you start scrolling, and it isn't consistent, but IMO that's much lower value than the fact that it was off the screen originally.

See the PR for screenshot examples.

@christopherdarling do you feel strongly enough that we should raise a new issue to tweak those positioning rules?

**Comment by christopherdarling** [comment] 2019-07-17 16:29
@robbieaverill I haven't had chance to test the PR but the screenshots look like a definite improvement.

Am I right in my understanding from your description on the PR that the issue (_that I raised here, and the positioning issue you mentioned that's still present on the PR_) only occurs in HtmlEditorField's with < 6 rows? If that's the case, perhaps change https://github.com/dnadesign/silverstripe-elemental/blob/6e04835688f3d45af21fa381e49c9cae0c647fc7/src/Forms/EditFormFactory.php#L40 to 6 or greater?

**Comment by robbieaverill** [comment] 2019-07-17 16:31
That's correct, however we've been using 5 rows as a conscious design decision. You can replace that class with Injector in your project code and change that to 6 rows to work around this issue while that PR is not available in a stable release, however.

**Comment by christopherdarling** [comment] 2019-07-17 16:40
Fair enough, although, given the usability issue of 5 rows with quite a common feature perhaps that's worth reconsidering? Although I'm sure there's good reason for you / the design team to reject this idea and if so, I'd say that fixing the positioning bug still present would be worthwhile.

**Comment by robbieaverill** [comment] 2019-07-17 16:41
Yep, fair comment - cc @silverstripeux

**Comment by ScopeyNZ** [comment] 2019-07-17 22:40
I've just merged the admin PR - I'll leave this open for now in case we decide that we want to increase the row count to get around the bug (or the weird behaviour of the popover covering the links). Perhaps we could drop the pretty much useless bottom bar?

**Comment by ScopeyNZ** [comment] 2019-07-17 23:09
Why does this exist here?:

https://github.com/dnadesign/silverstripe-elemental/blob/6e04835688f3d45af21fa381e49c9cae0c647fc7/src/Forms/EditFormFactory.php#L40

Anyway - here's a PR for consideration - including moving that weirdness to `ElementContent`:

#695

**Comment by clarkepaul** [comment] 2019-07-18 03:39
I don't really have an opinion on how many rows are required, but 20 that we used to have on pages would be way too many for content segments like blocks. Even if the row count was extended from 5 to say 8 the problem still exists. As long as people are able to see multiple blocks in the list for the majority of users its cool. Happy with the increase to 7 :)

**Comment by robbieaverill** [comment] 2019-07-22 09:05
>Why does this exist here?:

To clarify- the EditFormFactory applies to React forms, but not to Entwine forms. It's there because we want inline editable TinyMCE fields to be smaller than GridFieldDetailForm TinyMCE fields, which have more room to take up (this was discussed in the associated PR, but noting here for brevity).

**Comment by robbieaverill** [comment] 2019-07-22 09:29
The original bug is fixed in silverstripe/admin, and we've also removed the reason it occurs in elemental 4.1.x

**Closed by robbieaverill** 2019-07-22 09:29 UTC
Labels: affects/v4, change/patch, effort/medium, impact/medium, type/UX, type/bug
