### ISSUE TITLE
Keyboard accessibility on block editing

### ISSUE THREAD

**Issue by chillu** [dnadesign/silverstripe-elemental#626] opened 2019-03-08 02:59 UTC
* Focus on an unexpanded block by tabbing into it. I'd expect the ENTER key to expand the block for editing (if it's inline editable), or to open the detail view if it isn't
 * Continue tabbing into the block. The "settings" icon works as expected, but the "expand" button doesn't. It has no outline indicating focus, and when hitting ENTER it loads the "metadata" tab, not the "content" tab.

dnadesign/silverstripe-elemental                  4.0.x-dev dd8e73b

**Comment by ScopeyNZ** [comment] 2019-03-21 23:13
This is a regression:

https://github.com/dnadesign/silverstripe-elemental/blob/885496a08a1115d7c1144b9161858acb01e570b8/client/src/components/ElementEditor/Element.js#L159

The "Expand" button made no sense to be tabbed to because you should be able to already expand the block when you have the whole block focussed. From memory we explicitly decided to remove the tabindex on the expand button for that reason.

> and when hitting ENTER it loads the "metadata" tab, not the "content" tab.

I'm not able to reproduce this. Pressing <kbd>enter</kbd> on the settings "meatballs" opens the dropdown. <kbd>Tab</kbd>-ing takes me into that dropdown. Pressing <kbd>enter</kbd> or <kbd>space</kbd> in that menu performs the expected action.

**Comment by ScopeyNZ** [comment] 2019-03-21 23:34
I've raised a PR #643 that fixes the keyboard events.

**Comment by robbieaverill** [comment] 2019-03-22 00:47
Fixed with #643

**Closed by robbieaverill** 2019-03-22 00:47 UTC
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/UX, type/bug
