### ISSUE TITLE
Incorrect order on new created blocks

### ISSUE THREAD

**Issue by digitall-it** [dnadesign/silverstripe-elemental#594] opened 2019-02-05 16:02 UTC
I’m having some glitches in the Elemental 4 sort order. Seems like when I create a block, gets added to top of the stack of blocks, and appears in a different position in the frontend. To reorder everything correctly I have to jiggle back and forth almost all the blocks in the page in the CMS.

**Comment by robbieaverill** [comment] 2019-02-05 16:03
Could you please supply the version of elemental you're using?

**Comment by kinglozzer** [comment] 2019-02-05 16:46
Possibly a duplicate of https://github.com/dnadesign/silverstripe-elemental/issues/548? The fix for that hasn’t been tagged yet AFAICT

**Comment by digitall-it** [comment] 2019-02-05 17:13
I'm working on v4.0.1. As discussed on the Slack channel, the proposed course of action is to wait for 4.0.2, and if the problem is still there, output there some debug data (template and CMS `$Sort` number for each block).

**Comment by robbieaverill** [comment] 2019-02-06 19:51
@digitall-it are you able to try using `4.0.x-dev`? If it is working there then I'll tag a new release and problem solved

**Comment by ScopeyNZ** [comment] 2019-02-08 02:30
I'm going to close this as a duplicate of #548 . It is released now in `4.0.2`. We should have an upcoming `4.0.3` soon too.

**Closed by ScopeyNZ** 2019-02-08 02:30 UTC
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/UX, type/bug

**Comment by tardinha** [comment] 2019-03-21 02:53
I'm getting this. Newly created elements go to the top of the list of existing elements. However, on previous versions, new ones go to the end of the list. Maybe this is by design?

SS 4.3, Elemental 4.0.3

**Comment by kinglozzer** [comment] 2019-03-21 09:28
@tardinha That sounds like a different issue: https://github.com/dnadesign/silverstripe-elemental/issues/566

**Comment by tardinha** [comment] 2019-03-21 21:40
@kinglozzer sorry mate, didn't see that one! :)
