### ISSUE TITLE
Regression: Toast notifications lost

### ISSUE THREAD

**Issue by Cheddam** [dnadesign/silverstripe-elemental#794] opened 2020-05-01 00:32 UTC
### Overview

Toast notifications are not currently triggered for block operations performed in the inline editor. This is a regression, see: https://github.com/dnadesign/silverstripe-elemental/blob/4.3.2/client/src/components/ElementActions/SaveAction.js#L55-L65

### Implementation notes
- Ensure all notification logic currently present works as expected
- There are exisiting [designs](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5b8f33ec15093c001068254a) to give an indication to what's been built (but look at the code first)
- In the future, we'll look to refactor the code to use https://github.com/silverstripe/silverstripe-admin/issues/504, though given this would require 4.7, we'll ensure the jquery notification implementation works for now

**Comment by robbieaverill** [comment] 2020-05-01 02:45
This sounds like a regression rather than a feature... https://github.com/dnadesign/silverstripe-elemental/blob/4.3.2/client/src/components/ElementActions/SaveAction.js#L55-L65

**Comment by emteknetnz** [comment] 2020-08-03 00:29
I could not replicate in 
"silverstripe/recipe-cms": "4.5.x-dev",
"silverstripe/recipe-content-blocks": "2.5.x-dev"

Nor could not replicate in 
"silverstripe/recipe-cms": "4.6.x-dev",
"silverstripe/recipe-content-blocks": "2.6.x-dev"

Toast notifications worked for performing both inline actions on blocks, as well as actions on the whole page

@Cheddam are you able to provide replication steps?

**Comment by brynwhyman** [comment] 2020-08-04 20:30
Let's close this for now :)

**Closed by brynwhyman** 2020-08-04 20:30 UTC
Labels: affects/v4, effort/easy, impact/medium, type/UX, type/bug

**Comment by emteknetnz** [comment] 2020-08-05 03:02
Changed points from 3 to 1 since we never fixed it, only investigated
