### ISSUE TITLE
Versioning does not appear to work correctly

### ISSUE THREAD

**Issue by NightJar** [dnadesign/silverstripe-elemental#117] opened 2017-10-15 23:07 UTC
When editing an existing block on a published page, upon save the (Stage=live) page instantly updates to the new content, which is technically draft content.

Reproduction:
`composer create-project silverstripe/installer test 4.0.x-dev`
`composer require dnadesign/silverstripe-elemental 2.x-dev`

Add the appropriate config directive (note docs name `ElementPageExtension` when this should be `ElementalPageExtension` [note the `al`])
Update Simple theme's template to reference $ElementalArea

Create a new ContentElement block for the Home page.
Save some content.
Publish the page.
Alter the content block's content.
Save the content block.
Do _not_ publish the page.
Log out of the CMS.

Live site displays the updated (draft) content of the ContentElement.

**Comment by robbieaverill** [comment] 2017-10-31 00:04
Reproduced, however the draft content is not shown when viewing incognito.

I did notice however that after publishing a content block and the page it's on then updating the content and saving (not publishing) doesn't cause the page to be in a modified state.

**Comment by NightJar** [comment] 2017-10-31 20:31
Here we are. In the invisible container.
https://github.com/dnadesign/silverstripe-elemental/blob/master/src/Models/ElementalArea.php#L203

**Comment by robbieaverill** [comment] 2017-11-01 21:13
So at a quick look through the history of this module, it looks like the `getOwnerPage` method is a sort of catch all getter across versioned stages for different types of objects. The `OwnerClassName` has been added during the refactoring for SS4, and my suspicion is that it could be replaced with a polymorphic has_one relationship instead, which may also remove the need for `ElementalAreasExtension::getElementalRelations`, leaving us to use the SS ORM's default relationship methods instead.

Anyway, the line highlighted above exists from SS3 through to now, but isn't actually being fired. The page returned is from the line above:

```php
                if ($page && $page->exists()) {
                    return $page->first();
                }
```

At this point in the logic the Versioned stage is "Stage", where it should probably be "Live" since I'm not logged into the CMS.

**Comment by robbieaverill** [comment] 2017-11-01 21:32
Bit more digging: `Versioned::choose_site_stage` in VersionedHTTPMiddleware sets the stage to Stage rather than Live because the readingMode persists in the session after logging out:

```php
    public static function choose_site_stage(HTTPRequest $request)
    {
        // Check any pre-existing session mode
        $preexistingMode = $request->getSession()->get('readingMode') ?: static::DEFAULT_MODE;
        $mode = $preexistingMode;
```

**Comment by robbieaverill** [comment] 2017-11-01 21:42
This behaviour is semi-replicable in core, only I get forced to log in rather than directly shown the draft content

**Comment by NightJar** [comment] 2017-11-01 21:54
It seems to me that a session (or at least anything to do with being logged in) should be nuked on log-out. It's a little concerning that this isn't the case, if I'm honest.

**Comment by robbieaverill** [comment] 2017-11-01 22:11
Raised over at https://github.com/silverstripe/silverstripe-versioned/issues/62

**Comment by robbieaverill** [comment] 2017-11-01 22:53
Fixed by https://github.com/silverstripe/silverstripe-versioned/pull/63, will close since it'll be resolved in core

**Closed by robbieaverill** 2017-11-01 22:53 UTC
Labels: affects/v4, effort/medium, impact/critical, type/bug
