### ISSUE TITLE
Feature Request: add possibility to create custom summaries

### ISSUE THREAD

**Issue by derralf** [dnadesign/silverstripe-elemental#640] opened 2019-03-20 17:06 UTC
Please add a possibility to create custom summaries.

In version 3 the possibility was added to also use own frontend templates for the summaries:  [here](https://github.com/dnadesign/silverstripe-elemental/commit/99904d817a0766eca0319cfbde9d1dcb19cf7aa4)

For my own Elements I used this to display e.g. several thumbnails (elements with multiple images), information about style variation and other info in the summary.

Now that the summary is inserted via Javascript, only a one-liner is possible.

I think it would be helpful for editors if it were possible to show them "more meaningful" custom summaries.

**Comment by robbieaverill** [comment] 2019-03-20 19:53
Are you using Elemental v4? The summaries are configurable, but you likely need to use JavaScript to configure it rather than PHP. It sounds like we need some more documentation around how this works!

**Comment by ScopeyNZ** [comment] 2019-03-20 23:02
I'll close this as a duplicate of #582 . I will add a reference to this issue there.

**Closed by ScopeyNZ** 2019-03-20 23:02 UTC
