### ISSUE TITLE
Images added via HTMLEditorField not being published

### ISSUE THREAD

**Issue by Codesesh** [dnadesign/silverstripe-elemental#247] opened 2018-06-24 23:28 UTC
When using the block module and adding in the standard "Content" block, when adding images via the `HTMLEditorField` area, the image added is now being published, meaning when you view the page when logged out, the image is showing as broken.

This issue is related to this one that I created I believe: https://github.com/silverstripe/silverstripe-cms/issues/2200

**Comment by robbieaverill** [comment] 2018-06-24 23:44
Thanks for reporting. Closing as a duplicate of https://github.com/dnadesign/silverstripe-elemental/issues/210

**Closed by robbieaverill** 2018-06-24 23:44 UTC
