### ISSUE TITLE
Ensure new 'inline editing' form is compatible with Screen Readers

### ISSUE THREAD

**Issue by NightJar** [dnadesign/silverstripe-elemental#396] opened 2018-09-18 23:53 UTC
### Background
Aria roles currently exist to denote the form area as a form (because it's a div inside a form instead of it's own form, and a form in a form is not semantic to HTML). However it also is triggered to load (and hides) in an accordion style revel. This should also have applicable aria roles  to indicate that it can show and hide, and which control it corresponds to for that action.

### Overview
This issue was originally raised in September 2018. Since that time, accessibility improvements have been made, but mostly on an ad hoc basis. 

We should use an accessibility tool to run over v4 of the Elemental editor, identify areas for improvement, and begin resolving them as part of this issue.

### Acceptance criteria
- [x] An accessibility tool has been used to conduct a review; plus experimental testing
- [x] Findings are recorded in this issue
- [ ] Those that cannot be resolved within this timebox are raised separately

**Comment by robbieaverill** [comment] 2018-09-19 09:14
Are you talking about the toggle to expand the form or the form itself? Note that the "toggle" is the whole element, so be careful when adding aria labels to it

**Comment by NightJar** [comment] 2018-09-20 01:10
Yeah, the little hints and any other applicable attributes I guess. i.e. do a bit of a tiny audit.

**Comment by Cheddam** [comment] 2019-07-17 23:02
## Summary

I performed testing of the ElementalEditor UI using VoiceOver with Chrome, rather than our standard approach of testing basic keyboard accessibility. VoiceOver (VO) has its own actions for navigating interfaces, and unfortunately a lot of what we've done to enable keyboard accessibility is incompatible with VO. There are a variety of issues to address, with varying degrees of difficulty and importance. I've tried to order them by importance, and give an indication of the complexity.

**Notes:**

- Chrome's VoiceOver support has some weird bugs, so where I wasn't sure if an issue was with VO itself, I re-tested in Safari.
- VoiceOver has a fairly low, but not insignificant, share of the screen reader userbase. Guides I've read suggest that improving VoiceOver compatibility won't necessarily resolve issues for other implementations, so I'd like to cover JAWS / NVDA in the future.
- This may not cover every issue - it was tough to get past some limitations, so we might find some more issues to tackle once we've fixed those noted here.

## Discovered issues

### Description of blocks is verbose and unhelpful

The entire contents of the block are joined together when reading out the element, with no pauses, including the button labels. The label we've applied to the block itself is only read _after_ all of this.

**Steps to reproduce:**

1. Activate VoiceOver and use VO + → to shift the focus to a block
2. Observe excessively long and poor description provided by VoiceOver

### Opening / closing blocks does not work with VoiceOver

It's impossible to press the block "button" to expand it using the command VoiceOver describes. This instead opens the Actions menu, for some reason.

**Steps to reproduce:**

1. Activate VoiceOver and use VO + → to shift the focus to an inline-editable block
2. Press VO + Space to activate the block "button" (which should open the block for editing)
3. Observe the Actions menu is opened instead

### No audible indication when block is opened / closed

VoiceOver gives no announcement upon expanding / collapsing block when this is triggered via the implemented method (spacebar).

**Steps to reproduce:**

1. Activate VoiceOver and use VO + → to shift the focus to an inline-editable block
2. Press Space to open the block for editing
3. Observe that VoiceOver gives no indication anything has changed

### Impossible to navigate through block editor with VoiceOver

It's impossible to navigate to form elements within a block using VoiceOver's navigation commands when it has been opened.

**Steps to reproduce:**

1. Activate VoiceOver and use VO + → to shift the focus to an inline-editable block
2. Press Space to open the block for editing
3. Use VO + → to try and shift the focus to the form elements in the block, observe that the focus shifts to the next block or field below the ElementEditor
4. Use VO + Shift + ↓ to try to enter the scope of the block, observe that the focus is shifted to the "title" of the block but it's still not possible to navigate to the form elements

### Icon font results in arbitrary characters being read aloud

Our use of an icon font results in letters / numbers being read out in place of the icons. Notably, the `speak` CSS property is applied to the icons which should stop them from being read, but this seems to be ignored.

**Steps to reproduce:**

1. Activate VoiceOver and use VO + → to shift the focus to a block
2. Observe "seven" is randomly stated during the reading of the block contents (along with "s" if the drag/drop indicator is visible).

## Proposed actions

- Refactor the Element a11y structure
  - Ideally, the entire block should not act as the open/close toggle for keyboard access - instead, this behaviour should be on the arrow icon inside the block _(a click handler could still be applied to the full block)_
  - Use `aria-expanded` / `aria-controls` to designate whether the Element has been opened
  - Use `aria-labelledby` to designate the block title element as what should be announced when the block is selected
  - Add an sr-only span to the block title to designate it as a {type} block
    - e.g. `<h3 class="element-editor-header__title" id="block-title-2">Features <span class="sr-only">, Content Block</span></h3>`
  - Get the expanded Element view to be VoiceOver-navigable - not sure on how to achieve this yet, may be easier once the block is no longer a button
- Icon elements need to be hidden from SRs
  - They should be wrapped in another (button?) element (to be targeted by click events) with an SR-only full label element or title attribute

## General VoiceOver testing tips

- VoiceOver has a tutorial! FN + CTRL + Option + Command + 8
- CTRL + Option is the default "VoiceOver command" modifier combo (VO).
- VO + K puts VoiceOver in a mode where you can press key combinations to understand what they do.
- If the constant talking is distracting, you can mute VoiceOver! Open "VoiceOver Utility", and tick "Mute Speech" under the "Speech" tab.
- Chrome has some really weird bugs with VoiceOver - I caught it reading out information from inactive tabs.
- You can use the trackpad with VoiceOver! VO + clockwise rotation on the trackpad will switch it on. This provides a similar experience to how VoiceOver is used on iOS.

**Comment by NightJar** [comment] 2019-07-18 05:00
Nice write up, thanks @Cheddam 
It is probably worth mentioning at this point that VoiceOver! is Apple software, for Macs. NVDA is Windows based, and Google Vox is Chrome based (browser addon it seems).

**Comment by michalkleiner** [comment] 2019-07-18 05:17
I'm happy to see this level of thoroughness regarding accessibility within the elemental area. Is it something that might/should be expected from the framework itself? Clearly elemental is not the only interface requiring/benefiting from such attention.

**Comment by robbieaverill** [comment] 2019-07-22 09:08
@michalkleiner yep, that's the idea going forwards

**Comment by robbieaverill** [comment] 2019-07-22 09:08
@Cheddam there's one outstanding A/C:

>Those that cannot be resolved within this timebox are raised separately

Do you need to raise some new issues?

**Comment by Cheddam** [comment] 2019-07-23 00:24
I've put the required work into a new issue (#697). Closing this out.

**Closed by Cheddam** 2019-07-23 00:24 UTC
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/UX, type/bug
