### ISSUE TITLE
Need model validator error display

### ISSUE THREAD

**Issue by leochenftw** [dnadesign/silverstripe-elemental#805] opened 2020-06-11 05:00 UTC
And the moment, when `validate` throws an error message, the module doesn't nothing - you can see the error returned from graphql api, but the frontend doesn't pick up and display it

**Comment by ScopeyNZ** [comment] 2020-06-11 05:51
Thanks. Looks like it's a duplicate of https://github.com/dnadesign/silverstripe-elemental/issues/699. Please feel free to reopen if you think differently!

**Closed by ScopeyNZ** 2020-06-11 05:51 UTC
