### ISSUE TITLE
Changing sort-order does not get published.

### ISSUE THREAD

**Issue by bummzack** [dnadesign/silverstripe-elemental#177] opened 2018-01-22 20:19 UTC
Steps to reproduce:

1. Add some content-blocks
2. Publish everything
3. Sort the blocks to a different order
4. Publish the page again

While step 3 creates the proper sort order in the `Element` table, it does not get propagated to `Element_Live` upon publishing the page. 
Editing a single element and publishing it will properly update the sort order in the live table (but only for that element, all the others will still have the wrong value).

**Comment by robbieaverill** [comment] 2018-01-22 20:23
Hey @bummzack, ca you please provide the versions you're using? Thanks

**Comment by bummzack** [comment] 2018-01-22 20:26
Yeah, sorry:
dnadesign/silverstripe-elemental: **dev-master 49b8c14**
silverstripe/elemental-blocks: **dev-master cbfa21b**
silverstripe/recipe-cms: **1.0.1**

So basically the latest stable SS4 and both current master-branches of silverstripe-elemental and elemental-blocks.

**Comment by robbieaverill** [comment] 2018-01-22 20:26
Thanks!

**Comment by NightJar** [comment] 2018-02-09 03:58
Hi @bummzack - I cannot reproduce this issue on the latest master sorry.
`2.x-dev` @ 995c775

**Comment by NightJar** [comment] 2018-02-09 04:30
So looks like this is actually an issue with `symbiote/silverstripe-gridfieldextensions` and a small bug with SS4 `silverstripe/versioned` compatiblity.
It was fixed by https://github.com/symbiote/silverstripe-gridfieldextensions/pull/243 - however this is only on the `master` branch, where as `dnadesign/silverstripe-elemental` will install `^3.1` - this is an issue because the current master branch will eventually be stabilised as a new `4.x` line.

You can of course use this in the mean time, but we are looking to release a `3.2.0` of gridfieldextensions to get around this without a dependency major version bump.

**Closed** 2018-02-09 04:33 UTC
Labels: affects/v4, change/patch, effort/medium, impact/high, type/bug

**Comment by robbieaverill** [comment] 2018-02-11 22:14
You can update gridfieldextensions to 3.1.1 to get the fix for this https://github.com/symbiote/silverstripe-gridfieldextensions/releases/tag/3.1.1

**Comment by sirjeff** [comment] 2020-05-06 22:31
Hey just letting you know I have the same problem. Sort order is ok in stage but not live.
In stage the order is correct : 1,2,3,4,5,6,7,8 , but in the Element_Live table it shows as 1,2,2,3,3,4,5,5

silverstripe/recipe-cms - 4.5.0@stable
dnadesign/silverstripe-elemental - 4
symbiote/silverstripe-gridfieldextensions - 3.2

**Comment by sirjeff** [comment] 2020-05-06 23:05
I tried dnadesign/silverstripe-elemental - 4.0 same problem, so I jumped to 
dnadesign/silverstripe-elemental - 4.3
and now the order is saving correctly in Live. I had to change the order a few times before it kicked in though.
But "yah" it's working!

**Comment by brynwhyman** [comment] 2020-05-07 00:04
Hey @sirjeff I definitely recall this being a problem in previous versions of dnadesign/silverstripe-elemental 4.x but as you say it should be resolved now.

Some related issues and PRs that are now closed:
- https://github.com/dnadesign/silverstripe-elemental/issues/548
- https://github.com/dnadesign/silverstripe-elemental/issues/547
- https://github.com/dnadesign/silverstripe-elemental/pull/580
