### ISSUE TITLE
Replacing ElementalArea with Injector causes infinite loop when generating GraphQL admin schema

### ISSUE THREAD

**Issue by AljosaB** [dnadesign/silverstripe-elemental#1014] opened 2022-10-04 10:11 UTC
## Affected Version
SS 4.11.2
Elemental 4.9.4

## Steps to Reproduce
**/app/src/ChangedElementalArea.php**
```php
<?php

namespace Aljosa\DataObjects;

use DNADesign\Elemental\Models\ElementalArea;

class ChangedElementalArea extends ElementalArea
{
    // it happens even if there is no code here
}
```

**/app/_config/injectors.yml**
```yml
SilverStripe\Core\Injector\Injector:
  DNADesign\Elemental\Models\ElementalArea:
    class: Aljosa\DataObjects\ChangedElementalArea
```

**Run**
```bash
/vendor/silverstripe/framework$ php cli-script.php dev/graphql/build schema=admin flush=1
```
(which is also automatically executed every dev/build)

**Error**
```
[INFO]: --- Building schema "admin" ---
ERROR [Emergency]: Uncaught Error: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames
IN GET dev/graphql/build
Line 50 in /vendor/silverstripe/framework/src/Core/Injector/SilverStripeServiceConfigurationLocator.php
```

## Additional info
- it breaks loading all elemental areas in CMS (GraphQL ajax calls)
- it has something to do with

**/vendor/dnadesign/silverstripe-elemental/_graphql/models.yml**
```yml
# Expose access to Elements via Page -> ElementalArea -> Elements (see resolver)
DNADesign\Elemental\Models\ElementalArea:
  fields:
    id: true
    elements:
      plugins:
        paginateList: false
  operations:
    readOne: true
```

**Comment by lozcalver** [comment] 2023-03-14 15:53
@AljosaB Have you tried increasing your max depth setting in xdebug or disabling xdebug? I have (occasionally) encountered legitimate code that exceeds the default limit of 256 before

**Comment by AljosaB** [comment] 2023-03-15 10:29
I have debugged it step by step and can confirm that it gets into a function (can't remember which one atm) that recursively (and infinitely) calls itself over and over with same parameters.

Also, it seems like it's not a problem of elemental module, but rather graphql, so I think this is going to auto-resolve when silverstripe/silverstripe-graphql#524 is fixed.

**Comment by GuySartorelli** [comment] 2023-03-20 20:39
This feels a lot like a duplicate of https://github.com/silverstripe/silverstripe-graphql/issues/524. @AljosaB is there a reason this is open as a separate issue?
Edit: nevermind I just saw that you opened this one first. I'm going to close it as a duplicate (it seems like the main problem is the graphql issue) - but feel free to reopen if you think it's a separate problem.

**Closed as not planned** 2023-03-20 20:40 UTC
Labels: type/bug, affects/v4, impact/medium, affects/v5
